name: Build QMK firmware
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    strategy:
      fail-fast: false

    steps:

    - name: Disable git safe directory checks
      run : git config --global --add safe.directory '*'

    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: krishbinpaudel/qmk_firmware
        submodules: recursive
        ref: k8_bt_port_squash

    - name: Checkout userspace
      uses: actions/checkout@v3
      with:
        path: users/${{ github.actor }}
    
    - name: Install dependencies
      run: qmk setup

    - name: Install dependencies
      run: python3 -m pip install -r /__w/qmk_firmware/qmk_firmware/requirements.txt

    - name: Build firmware
      run: qmk compile -kb keychron/k8_bt/rgb/ansi -km krishbin

    - name: Archive firmware
      uses: actions/upload-artifact@v4
      continue-on-error: true
      with:
        include-hidden-files: true
        overwrite: true
        name: k8_bt_firmware
        path: |
          .build/*.hex
          .build/*.bin
          .build/*.uf2
          .build/*.elf
